config/routes.rb
Bloccit::Application.routes.draw do

  resources :posts, only: [:index]
  resources :topics do
    resources :posts, except: [:index], controller: 'topics/posts' do
      resources :comments, only: [:create, :destroy]
      match '/up-vote', to: 'votes#up_vote', as: :up_vote
      match '/down-vote', to: 'votes#down_vote', as: :down_vote
      resources :favorites, only: [:create, :destroy]
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  resources :users, only: [:show, :index]

  match "about" => 'welcome#about', via: :get

  root :to => 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocit</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="padding-top: 70px">
<div class="container">
  <nav class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <a class="brand" style="margin-left: 20px; color: #000; font-weight: bold; text-shadow: 0px 0px 10px #999" href="<%= root_path %>">BLOCCIT</a>
      <ul class="nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Topics", topics_path %></li>
        <li><%= link_to "Popular", posts_path %></li>
        <li><%= link_to "Users", users_path %></li>
      </ul>
      <ul class="pull-right nav">
        <% if current_user %>
            <li class="nav-text"><%= get_avtar('tiny') %></li>
            <li class="dropdown"><a class="dropdown-toggle" href="#" data-toggle="dropdown"><%= current_user.name || current_user.email %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to edit_user_registration_path do %><span class="icon-user"></span> Profile<% end %></li>
                  <li><a href="<%= users_path %>/<%= current_user.id %>"><span class="icon-list"></span> Public Profile</a></li>
                  <li class="divider"></li>
                  <li><%= link_to destroy_user_session_path, method: :delete do %><span class="icon-remove-circle"></span> Sign Out<% end %></li>
                </ul>
            </li>
        <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>


  <div id="alerts">
  <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
  <% elsif flash[:error] %>
      <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
  <% elsif flash[:alert] %>
      <div class="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
  <% end %>
  </div>

  <%= yield %>
</div>

</body>
</html>